# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
    ]
